import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";

const instrumentSans = Instrument_Sans({
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${instrumentSans.className} antialiased`}>
                <div className="h-screen flex justify-center items-center max-w-full overflow-y-scroll">
                    <div className="md:w-[600px] h-full w-full">{children}</div>
                    {/* temp for mobile force to desktop */}
                </div>
            </body>
        </html>
    );
}
